name: Kuppi Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r kuppi-server/requirements.txt
          pip install pytest

      - name: Set Environment Variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV  # Optional: Set testing mode

      - name: Run Tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # Ensure secrets are loaded in test runtime
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)/kuppi-server
          pytest kuppi-server/tests/
