name: Kuppi Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Start MongoDB
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:latest

      - name: Wait for MongoDB to be ready
        run: |
          docker exec mongodb mongo --eval "db.runCommand({ connectionStatus: 1 })"

      - name: Set Environment Variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=supersecretkey" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://localhost:27017/testdb" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r kuppi-server/requirements.txt
          pip install pytest

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Run Tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)/kuppi-server
          pytest --maxfail=1 --disable-warnings -v kuppi-server/tests/
