name: Kuppi Server CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Start MongoDB
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:latest

      - name: Set Environment Variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=supersecretkey" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://localhost:27017/testdb" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r kuppi-server/requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)/kuppi-server
          pytest kuppi-server/tests/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Flask Backend to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up --ci --service kuppi-server


